// Dedicated MyScoreIQ tri-merge text parser.
//
// Input: text extracted from a MyScoreIQ PDF (`parseReportPdf`) or
// stripped from a saved HTML page. Output: plain JSON in the exact
// shape the existing MyScoreIQ JSON adapter
// (`lib/credit-import/providers/identityiq.ts`) consumes — which means
// once we have this JSON, the customer's upload flows through the same
// `createImport → captureRaw → runNormalization` pipeline as a
// directly-saved JSON, gets dispute candidates generated by the
// existing dispute engine, and lands on the customer's results page
// without any new persistence code.
//
// This is intentionally a separate module from the generic
// `lib/report-parser.ts` heuristic parser. That one was a best-effort
// tri-merge / line-scan parser; this one knows MyScoreIQ's specific
// section layout (Personal Information, Credit Score, Summary, Account
// History, Inquiries, Creditor Contacts, Public Records, Collections)
// and is built to be evolved alongside MyScoreIQ's actual report
// format.
//
// Confidence model: every parse returns a `confidence` value
//   - "high"   → ≥3 tradelines AND found at least one bureau score AND
//                detected a plausible name in personal info.
//   - "medium" → some tradelines but missing scores or personal info.
//   - "low"    → no tradelines extracted. Caller should treat as
//                "needs_manual_review" and present the friendly
//                "support is reviewing" copy to the customer rather
//                than an error.
//
// The parser never throws. Bad input degrades to an empty/low-confidence
// result; the caller decides what to do.

export type MyScoreIQParsedJson = {
  reportId?: string;
  reportDate?: string;
  borrower?: {
    fullName?: string;
    firstName?: string;
    lastName?: string;
    dateOfBirth?: string;
    ssn?: string;
    currentAddress?: {
      line1?: string;
      city?: string;
      state?: string;
      zip?: string;
    };
    phone?: string;
    priorAddresses?: Array<{
      line1?: string;
      city?: string;
      state?: string;
      zip?: string;
    }>;
    employers?: Array<{
      name?: string;
      position?: string;
      dateReported?: string;
    }>;
    consumerStatement?: string;
  };
  creditScores?: Array<{
    bureau: "Experian" | "Equifax" | "TransUnion";
    model?: string;
    score: number;
    date?: string;
    factors?: string[];
  }>;
  tradelines?: Array<{
    bureau: "Experian" | "Equifax" | "TransUnion";
    creditorName: string;
    accountNumber?: string;
    accountType?: string;
    balance?: number;
    highBalance?: number;
    creditLimit?: number;
    pastDue?: number;
    monthlyPayment?: number;
    status?: string;
    dateOpened?: string;
    lastReported?: string;
    lastActivity?: string;
    paymentHistory?: Array<{ month: string; code: string }>;
    isCollection?: boolean;
    isChargeOff?: boolean;
    isMedical?: boolean;
    isDerogatory?: boolean;
    isClosed?: boolean;
    remarks?: string[];
  }>;
  inquiries?: Array<{
    bureau: "Experian" | "Equifax" | "TransUnion";
    subscriberName: string;
    inquiryDate?: string;
    hardInquiry?: boolean;
    type?: string;
  }>;
  collections?: Array<{
    bureau: "Experian" | "Equifax" | "TransUnion";
    collectorName: string;
    originalCreditor?: string;
    accountNumber?: string;
    balance?: number;
    originalBalance?: number;
    status?: string;
    dateAssigned?: string;
    dateOfFirstDelinquency?: string;
    dateReported?: string;
    isMedical?: boolean;
  }>;
  publicRecords?: Array<{
    bureau: "Experian" | "Equifax" | "TransUnion";
    recordType: string;
    status?: string;
    courtName?: string;
    referenceNumber?: string;
    dateFiled?: string;
    amount?: number;
  }>;
};

export type MyScoreIQParseResult = {
  json: MyScoreIQParsedJson;
  confidence: "high" | "medium" | "low";
  reasonCodes: string[];
  counts: {
    tradelines: number;
    inquiries: number;
    collections: number;
    publicRecords: number;
    scores: number;
  };
};

type Bureau = "Experian" | "Equifax" | "TransUnion";

// ── Section markers ─────────────────────────────────────────────────────
//
// Listed in the order they typically appear in a MyScoreIQ PDF. The
// parser uses these to slice the text into per-section chunks before
// running section-specific extractors. Each entry is matched
// case-insensitively at the start of a line (or after a vertical
// whitespace boundary).
type SectionKey =
  | "personal"
  | "score"
  | "summary"
  | "accounts"
  | "inquiries"
  | "publicRecords"
  | "collections"
  | "contacts";

const SECTION_PATTERNS: Array<{ key: SectionKey; pattern: RegExp }> = [
  {
    key: "personal",
    pattern: /^\s*(?:personal\s+information|consumer\s+information|personal\s+profile)\s*$/im,
  },
  {
    key: "score",
    pattern: /^\s*(?:credit\s+scores?|fico\s+scores?|vantage\s+scores?)\s*$/im,
  },
  { key: "summary", pattern: /^\s*(?:credit\s+)?summary\s*$/im },
  {
    key: "accounts",
    pattern: /^\s*(?:account\s+history|accounts?|tradelines?|revolving\s+accounts?|installment\s+accounts?|open\s+accounts?)\s*$/im,
  },
  { key: "inquiries", pattern: /^\s*(?:inquiries|hard\s+inquiries|recent\s+inquiries)\s*$/im },
  {
    key: "publicRecords",
    pattern: /^\s*public\s+records?\s*$/im,
  },
  {
    key: "collections",
    pattern: /^\s*(?:collection\s+accounts?|collections)\s*$/im,
  },
  {
    key: "contacts",
    pattern: /^\s*(?:creditor\s+contacts?|creditor\s+addresses)\s*$/im,
  },
];

// ── Public entry point ──────────────────────────────────────────────────
export function parseMyScoreIQText(rawText: string): MyScoreIQParseResult {
  const reasonCodes: string[] = [];
  const text = preprocess(rawText);

  if (!text || text.length < 50) {
    return emptyResult(["EMPTY_TEXT"]);
  }

  const sections = sliceSections(text);
  if (Object.keys(sections).length === 0) {
    reasonCodes.push("NO_SECTIONS_DETECTED");
  }

  const json: MyScoreIQParsedJson = {};

  // Personal information
  if (sections.personal) {
    const borrower = parsePersonalInformation(sections.personal);
    if (borrower) json.borrower = borrower;
  }
  if (!json.borrower) {
    // Fall back: grab name/address/phone from the very top of the
    // document, where MyScoreIQ also prints them.
    const fallbackBorrower = parsePersonalInformation(text.slice(0, 1500));
    if (fallbackBorrower && fallbackBorrower.fullName) {
      json.borrower = fallbackBorrower;
    }
  }

  // Credit scores
  if (sections.score) {
    const scores = parseCreditScores(sections.score);
    if (scores.length) json.creditScores = scores;
  }
  if (!json.creditScores || json.creditScores.length === 0) {
    const scores = parseCreditScores(text);
    if (scores.length) json.creditScores = scores;
  }

  // Tradelines
  if (sections.accounts) {
    json.tradelines = parseAccountHistory(sections.accounts);
  } else {
    // Sometimes the entire body is one big "Account History" with no
    // explicit header (older MyScoreIQ exports).
    json.tradelines = parseAccountHistory(text);
  }

  // Collections (often inside Account History too — merge any we find
  // here with the ones tagged isCollection in tradelines).
  if (sections.collections) {
    json.collections = parseCollections(sections.collections);
  }

  // Inquiries
  if (sections.inquiries) {
    json.inquiries = parseInquiries(sections.inquiries);
  }

  // Public records
  if (sections.publicRecords) {
    json.publicRecords = parsePublicRecords(sections.publicRecords);
  }

  // Report metadata
  const pulledMatch = text.match(
    /(?:report\s+date|pulled|generated|as\s+of)\s*[:\-]?\s*(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})/i,
  );
  if (pulledMatch) {
    json.reportDate = isoDate(pulledMatch[1]);
  }

  const counts = {
    tradelines: json.tradelines?.length ?? 0,
    inquiries: json.inquiries?.length ?? 0,
    collections: json.collections?.length ?? 0,
    publicRecords: json.publicRecords?.length ?? 0,
    scores: json.creditScores?.length ?? 0,
  };

  // Confidence scoring.
  let confidence: "high" | "medium" | "low" = "low";
  if (counts.tradelines >= 3 && counts.scores > 0 && json.borrower?.fullName) {
    confidence = "high";
  } else if (counts.tradelines > 0) {
    confidence = "medium";
  }
  if (counts.tradelines === 0) reasonCodes.push("NO_TRADELINES_PARSED");
  if (counts.scores === 0) reasonCodes.push("NO_SCORES_PARSED");
  if (!json.borrower?.fullName) reasonCodes.push("NO_BORROWER_NAME");

  return { json, confidence, reasonCodes, counts };
}

function emptyResult(reasonCodes: string[]): MyScoreIQParseResult {
  return {
    json: {},
    confidence: "low",
    reasonCodes,
    counts: {
      tradelines: 0,
      inquiries: 0,
      collections: 0,
      publicRecords: 0,
      scores: 0,
    },
  };
}

// ── Preprocessing ───────────────────────────────────────────────────────
function preprocess(raw: string): string {
  return raw
    // Normalize line endings.
    .replace(/\r\n?/g, "\n")
    // PDF-extracted text often joins words across page breaks with a
    // hyphen-space; stitch those back together so regex doesn't miss.
    .replace(/-\s*\n\s*/g, "")
    // Collapse runs of spaces (but keep newlines).
    .replace(/[ \t]+/g, " ")
    // Trim trailing whitespace per line.
    .split("\n")
    .map((l) => l.trim())
    .join("\n")
    // Collapse 3+ newlines down to 2 (paragraph break).
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// ── Section slicing ─────────────────────────────────────────────────────
function sliceSections(text: string): Partial<Record<SectionKey, string>> {
  type Marker = { key: SectionKey; index: number; matchLen: number };
  const markers: Marker[] = [];
  for (const { key, pattern } of SECTION_PATTERNS) {
    const m = text.match(pattern);
    if (m && m.index !== undefined) {
      markers.push({ key, index: m.index, matchLen: m[0].length });
    }
  }
  markers.sort((a, b) => a.index - b.index);
  const out: Partial<Record<SectionKey, string>> = {};
  for (let i = 0; i < markers.length; i++) {
    const cur = markers[i];
    const next = markers[i + 1];
    const start = cur.index + cur.matchLen;
    const end = next ? next.index : text.length;
    out[cur.key] = text.slice(start, end).trim();
  }
  return out;
}

// ── Personal Information ────────────────────────────────────────────────
function parsePersonalInformation(
  block: string,
): MyScoreIQParsedJson["borrower"] | undefined {
  const borrower: NonNullable<MyScoreIQParsedJson["borrower"]> = {};

  const nameMatch = block.match(
    /^(?:name|consumer\s+name|primary\s+name|full\s+name)\s*[:\-]\s*([^\n]+)$/im,
  );
  if (nameMatch) borrower.fullName = nameMatch[1].trim();

  const ssnMatch = block.match(
    /(?:ssn|social\s+security)[^\n]*?([Xx*\d]{3}[-\s]?[Xx*\d]{2}[-\s]?\d{4})/i,
  );
  if (ssnMatch) borrower.ssn = ssnMatch[1];

  const dobMatch = block.match(
    /(?:date\s+of\s+birth|d\.?o\.?b\.?|birth\s*date)\s*[:\-]?\s*(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})/i,
  );
  if (dobMatch) borrower.dateOfBirth = isoDate(dobMatch[1]);

  const phoneMatch = block.match(
    /(?:phone|telephone)\s*[:\-]?\s*\(?(\d{3})\)?[\s\-]?(\d{3})[\s\-]?(\d{4})/i,
  );
  if (phoneMatch) {
    borrower.phone = `${phoneMatch[1]}-${phoneMatch[2]}-${phoneMatch[3]}`;
  }

  const addressMatch = block.match(
    /(?:current\s+address|address|residence)\s*[:\-]?\s*([^\n]+?)(?:[\n]|$)/i,
  );
  if (addressMatch) {
    const addr = parseAddress(addressMatch[1]);
    if (addr) borrower.currentAddress = addr;
  }

  const employerMatch = block.match(
    /(?:employer|employment)\s*[:\-]?\s*([^\n]+?)(?:[\n]|$)/i,
  );
  if (employerMatch) {
    borrower.employers = [{ name: employerMatch[1].trim() }];
  }

  // Return undefined if we found nothing meaningful — let the caller
  // fall back to a different region of the document.
  if (Object.keys(borrower).length === 0) return undefined;
  return borrower;
}

function parseAddress(line: string):
  | NonNullable<NonNullable<MyScoreIQParsedJson["borrower"]>["currentAddress"]>
  | undefined {
  // Common formats:
  //   "123 Main St, Anytown, CA 90210"
  //   "123 Main St Anytown CA 90210"
  //   "123 Main St / Anytown / CA / 90210"
  const m = line.match(
    /^(.+?)[,\/\|\s]+([A-Z][A-Za-z\s\.]+?)[,\/\|\s]+([A-Z]{2})\s+(\d{5}(?:-\d{4})?)\s*$/,
  );
  if (!m) return undefined;
  return {
    line1: m[1].trim(),
    city: m[2].trim(),
    state: m[3].trim(),
    zip: m[4].trim(),
  };
}

// ── Credit Scores ───────────────────────────────────────────────────────
function parseCreditScores(
  block: string,
): NonNullable<MyScoreIQParsedJson["creditScores"]> {
  const out: NonNullable<MyScoreIQParsedJson["creditScores"]> = [];
  // Pattern matches "Experian: 720 (FICO 8)" / "Equifax 715 FICO 8" /
  // "TransUnion FICO 8 738" etc. Be liberal with separators.
  const lineRegex = /(experian|equifax|trans\s*union|transunion)\b[\s\S]{0,80}?(\d{3})\b/gi;
  const seenBureaus = new Set<Bureau>();
  let m: RegExpExecArray | null;
  while ((m = lineRegex.exec(block)) !== null) {
    const bureau = canonicalBureau(m[1]);
    if (!bureau) continue;
    const score = Number(m[2]);
    if (score < 300 || score > 850) continue;
    if (seenBureaus.has(bureau)) continue;
    seenBureaus.add(bureau);
    // Try to capture a model name in the surrounding window.
    const window = block.slice(
      Math.max(0, m.index - 30),
      Math.min(block.length, m.index + 100),
    );
    const modelMatch = window.match(/(FICO\s*\d+|Vantage\s*\d?(?:\.\d)?)/i);
    out.push({
      bureau,
      score,
      model: modelMatch ? modelMatch[1].toUpperCase().replace(/\s+/g, " ") : "FICO 8",
    });
  }
  return out;
}

// ── Account History (tradelines) ────────────────────────────────────────
function parseAccountHistory(
  block: string,
): NonNullable<MyScoreIQParsedJson["tradelines"]> {
  const out: NonNullable<MyScoreIQParsedJson["tradelines"]> = [];
  // Strategy: split on blank-line boundaries; for each chunk, try to
  // detect whether it's an account block by looking for an "Account" /
  // "Account #" / "Account Number" label inside.
  const chunks = block
    .split(/\n\s*\n/)
    .map((c) => c.trim())
    .filter((c) => c.length > 0);

  for (const chunk of chunks) {
    if (!looksLikeAccountBlock(chunk)) continue;
    const tls = parseAccountBlock(chunk);
    out.push(...tls);
  }

  // Fallback: if no chunks parsed but the section is non-empty, try to
  // scan top-down for "Creditor: ..." labelled blocks separated by a
  // single newline.
  if (out.length === 0) {
    const labeledChunks = block.split(/\n(?=\s*(?:creditor|account)\s*[:\-])/i);
    for (const c of labeledChunks) {
      if (!looksLikeAccountBlock(c)) continue;
      out.push(...parseAccountBlock(c));
    }
  }

  return out;
}

function looksLikeAccountBlock(chunk: string): boolean {
  return (
    /(account\s*(?:number|#)|acct\s*#|^Account\s+|tradeline)/im.test(chunk) &&
    /(experian|equifax|trans\s*union|transunion)/i.test(chunk)
  );
}

function parseAccountBlock(
  chunk: string,
): NonNullable<MyScoreIQParsedJson["tradelines"]> {
  // Identify the creditor name. Three strategies, in priority order:
  //   1. Explicit "Creditor: ACME BANK" label.
  //   2. First non-empty line, if it doesn't look like a label.
  //   3. Any all-caps line of 3+ words.
  let creditorName: string | null = null;
  const creditorMatch = chunk.match(
    /(?:creditor|company\s+name|furnisher)\s*[:\-]\s*([^\n]+)/i,
  );
  if (creditorMatch) creditorName = creditorMatch[1].trim();
  if (!creditorName) {
    const firstLine = chunk.split("\n", 1)[0]?.trim() ?? "";
    if (firstLine && !/[:\-]/.test(firstLine) && firstLine.length < 60) {
      creditorName = firstLine;
    }
  }
  if (!creditorName) return [];

  const accountNumber = labelValue(chunk, [
    "account number",
    "account #",
    "account",
    "acct #",
  ]);
  const accountType = labelValue(chunk, [
    "account type",
    "type",
    "loan type",
  ]);
  const monthlyPayment = currencyValue(chunk, [
    "monthly payment",
    "min payment",
    "payment",
  ]);
  const dateOpened = dateValue(chunk, [
    "date opened",
    "opened",
    "open date",
  ]);
  const lastReported = dateValue(chunk, [
    "last reported",
    "reported",
    "date reported",
  ]);
  const lastActivity = dateValue(chunk, [
    "last activity",
    "activity",
    "date of last activity",
  ]);
  const remarksLine = labelValue(chunk, [
    "comments",
    "remarks",
    "consumer comment",
  ]);
  const remarks = remarksLine ? [remarksLine] : undefined;
  const paymentHistory = parsePaymentHistory(chunk);

  // For every bureau mentioned in the block, emit one tradeline. This
  // matches the JSON adapter's per-bureau row model. Per-bureau values
  // might differ in the source PDF; if we can't tell them apart we use
  // the same numbers for all three (better than dropping the row).
  const tradelines: NonNullable<MyScoreIQParsedJson["tradelines"]> = [];
  const bureausInBlock = detectBureausInBlock(chunk);

  for (const bureau of bureausInBlock) {
    const status = perBureauValue(chunk, bureau, [
      "status",
      "account status",
      "payment status",
    ]) ?? labelValue(chunk, ["status", "account status", "payment status"]);
    const balance = perBureauCurrency(chunk, bureau, ["balance"]) ??
      currencyValue(chunk, ["balance", "current balance"]);
    const highBalance = perBureauCurrency(chunk, bureau, [
      "high balance",
      "high credit",
    ]) ?? currencyValue(chunk, ["high balance", "high credit"]);
    const creditLimit = perBureauCurrency(chunk, bureau, [
      "credit limit",
      "limit",
    ]) ?? currencyValue(chunk, ["credit limit", "limit"]);
    const pastDue = perBureauCurrency(chunk, bureau, ["past due"]) ??
      currencyValue(chunk, ["past due", "amount past due"]);

    const flags = derogatoryFlags(status, accountType, creditorName, paymentHistory);

    tradelines.push({
      bureau,
      creditorName,
      accountNumber: accountNumber ?? undefined,
      accountType: accountType ?? undefined,
      balance,
      highBalance,
      creditLimit,
      pastDue,
      monthlyPayment,
      status: status ?? undefined,
      dateOpened,
      lastReported,
      lastActivity,
      paymentHistory,
      ...flags,
      remarks,
    });
  }

  return tradelines;
}

function detectBureausInBlock(chunk: string): Bureau[] {
  const out: Bureau[] = [];
  if (/\bexperian\b/i.test(chunk)) out.push("Experian");
  if (/\bequifax\b/i.test(chunk)) out.push("Equifax");
  if (/\btrans\s*union\b/i.test(chunk)) out.push("TransUnion");
  return out;
}

// "Status" line that appears under a per-bureau header (e.g. a 3-column
// MyScoreIQ tri-merge). Falls back to the whole-block value when the
// per-bureau lookup misses.
function perBureauValue(
  chunk: string,
  bureau: Bureau,
  labels: string[],
): string | undefined {
  // Find the bureau header, then look for the next line that starts
  // with one of the labels.
  const idx = chunk.toLowerCase().indexOf(bureau.toLowerCase());
  if (idx < 0) return undefined;
  const window = chunk.slice(idx, idx + 800);
  return labelValue(window, labels) ?? undefined;
}

function perBureauCurrency(
  chunk: string,
  bureau: Bureau,
  labels: string[],
): number | undefined {
  const idx = chunk.toLowerCase().indexOf(bureau.toLowerCase());
  if (idx < 0) return undefined;
  const window = chunk.slice(idx, idx + 800);
  return currencyValue(window, labels);
}

// MyScoreIQ payment-history strings look like "OK OK 30 60 OK" or
// "CCCCCCC1234". Map each token to a canonical code per FCRA: "C" =
// current, "30"/"60"/"90"/"120"/"150"/"180" = days late, "CO" = charge
// off, "ND" = no data.
function parsePaymentHistory(
  chunk: string,
): NonNullable<MyScoreIQParsedJson["tradelines"]>[number]["paymentHistory"] {
  const m = chunk.match(/(?:payment\s+history|two[\-\s]year\s+payment\s+history)\s*[:\-]?\s*([^\n]+)/i);
  if (!m) return undefined;
  const raw = m[1].trim();
  const tokens = raw.split(/\s+|,/).filter(Boolean);
  if (tokens.length === 0) return undefined;
  const out: NonNullable<
    NonNullable<MyScoreIQParsedJson["tradelines"]>[number]["paymentHistory"]
  > = [];
  for (let i = 0; i < tokens.length && i < 24; i++) {
    const t = tokens[i].toUpperCase();
    let code: string;
    if (/^OK|C+$/i.test(t) || t === "OK" || /^C+$/i.test(t)) code = "OK";
    else if (/^30/.test(t)) code = "30";
    else if (/^60/.test(t)) code = "60";
    else if (/^90/.test(t)) code = "90";
    else if (/^120/.test(t)) code = "120";
    else if (/^150/.test(t)) code = "150";
    else if (/^180/.test(t)) code = "180";
    else if (/^CO|CHARGE/.test(t)) code = "CO";
    else code = t.slice(0, 4);
    out.push({ month: String(i + 1), code });
  }
  return out;
}

function derogatoryFlags(
  status: string | undefined | null,
  accountType: string | undefined | null,
  creditorName: string | undefined | null,
  paymentHistory:
    | NonNullable<MyScoreIQParsedJson["tradelines"]>[number]["paymentHistory"]
    | undefined,
): {
  isCollection?: boolean;
  isChargeOff?: boolean;
  isMedical?: boolean;
  isDerogatory?: boolean;
  isClosed?: boolean;
} {
  const blob = `${status ?? ""} ${accountType ?? ""} ${creditorName ?? ""}`.toLowerCase();
  const isCollection = /collection|collections|chargeoff\s+to\s+collection|placed\s+for\s+collection/.test(
    blob,
  );
  const isChargeOff = /charge[\s\-]?off|charged[\s\-]?off|profit\s+and\s+loss/.test(blob);
  const isMedical = /\bmedical\b|hospital|dental|clinic|physician/.test(blob);
  const isClosed = /\bclosed\b|account\s+closed|paid\s+and\s+closed/.test(blob);
  const hasLate = (paymentHistory ?? []).some((p) =>
    /^(30|60|90|120|150|180|CO)/.test(p.code),
  );
  const isDerogatory =
    isCollection ||
    isChargeOff ||
    hasLate ||
    /past\s+due|delinquent|late|foreclosure|repossession|repo|bankruptcy/.test(blob);
  const out: ReturnType<typeof derogatoryFlags> = {};
  if (isCollection) out.isCollection = true;
  if (isChargeOff) out.isChargeOff = true;
  if (isMedical) out.isMedical = true;
  if (isClosed) out.isClosed = true;
  if (isDerogatory) out.isDerogatory = true;
  return out;
}

// ── Inquiries ───────────────────────────────────────────────────────────
function parseInquiries(
  block: string,
): NonNullable<MyScoreIQParsedJson["inquiries"]> {
  const out: NonNullable<MyScoreIQParsedJson["inquiries"]> = [];
  const lines = block
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  for (const line of lines) {
    // Common shapes:
    //   "Chase Bank - 03/15/2026 - Hard - Experian"
    //   "Chase Bank   03/15/2026   Experian"
    //   "Experian: Chase Bank 03/15/2026"
    //   "03/15/2026  Chase Bank  Hard  Experian"
    const dateMatch = line.match(/(\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})/);
    if (!dateMatch) continue;
    const bureauMatch = line.match(/\b(experian|equifax|trans\s*union|transunion)\b/i);
    if (!bureauMatch) continue;
    const bureau = canonicalBureau(bureauMatch[1])!;
    const isHard = !/\bsoft\b|account\s+review/i.test(line);
    // The inquirer is whatever's left after we strip the date + bureau
    // + "hard"/"soft" tokens.
    const subscriberName = line
      .replace(dateMatch[0], "")
      .replace(/\b(experian|equifax|trans\s*union|transunion)\b/gi, "")
      .replace(/\b(hard|soft|account\s+review)\b/gi, "")
      .replace(/[\-\|:,]+/g, " ")
      .replace(/\s+/g, " ")
      .trim();
    if (!subscriberName) continue;
    out.push({
      bureau,
      subscriberName,
      inquiryDate: isoDate(dateMatch[1]),
      hardInquiry: isHard,
    });
  }
  return out;
}

// ── Collections ─────────────────────────────────────────────────────────
function parseCollections(
  block: string,
): NonNullable<MyScoreIQParsedJson["collections"]> {
  const out: NonNullable<MyScoreIQParsedJson["collections"]> = [];
  const chunks = block
    .split(/\n\s*\n/)
    .map((c) => c.trim())
    .filter((c) => c.length > 0);
  for (const chunk of chunks) {
    const collectorMatch = chunk.match(
      /(?:collector|collection\s+agency|company)\s*[:\-]\s*([^\n]+)/i,
    );
    const firstLine = chunk.split("\n", 1)[0]?.trim() ?? "";
    const collectorName = (collectorMatch?.[1] ?? firstLine).trim();
    if (!collectorName) continue;
    const bureaus = detectBureausInBlock(chunk);
    if (bureaus.length === 0) continue;
    const accountNumber = labelValue(chunk, ["account number", "account #"]);
    const balance = currencyValue(chunk, ["balance", "current balance"]);
    const originalBalance = currencyValue(chunk, ["original balance"]);
    const originalCreditor = labelValue(chunk, [
      "original creditor",
      "creditor",
    ]);
    const dateAssigned = dateValue(chunk, [
      "date assigned",
      "assigned",
    ]);
    const dateOfFirstDelinquency = dateValue(chunk, [
      "date of first delinquency",
      "first delinquency",
      "dofd",
    ]);
    const dateReported = dateValue(chunk, ["date reported", "reported"]);
    const status = labelValue(chunk, ["status"]);
    const isMedical = /\bmedical\b|hospital|dental|clinic/i.test(chunk);
    for (const bureau of bureaus) {
      out.push({
        bureau,
        collectorName,
        originalCreditor: originalCreditor ?? undefined,
        accountNumber: accountNumber ?? undefined,
        balance,
        originalBalance,
        status: status ?? undefined,
        dateAssigned,
        dateOfFirstDelinquency,
        dateReported,
        isMedical,
      });
    }
  }
  return out;
}

// ── Public Records ──────────────────────────────────────────────────────
function parsePublicRecords(
  block: string,
): NonNullable<MyScoreIQParsedJson["publicRecords"]> {
  const out: NonNullable<MyScoreIQParsedJson["publicRecords"]> = [];
  const chunks = block
    .split(/\n\s*\n/)
    .map((c) => c.trim())
    .filter((c) => c.length > 0);
  for (const chunk of chunks) {
    const typeMatch = chunk.match(
      /(bankruptcy|tax\s+lien|civil\s+judgment|judgment|lien|foreclosure)/i,
    );
    if (!typeMatch) continue;
    const bureaus = detectBureausInBlock(chunk);
    if (bureaus.length === 0) continue;
    const dateFiled = dateValue(chunk, [
      "date filed",
      "filed",
      "filing date",
    ]);
    const courtName = labelValue(chunk, ["court", "court name"]);
    const status = labelValue(chunk, ["status"]);
    const referenceNumber = labelValue(chunk, [
      "reference",
      "reference number",
      "case number",
      "docket",
    ]);
    const amount = currencyValue(chunk, ["amount", "liability"]);
    for (const bureau of bureaus) {
      out.push({
        bureau,
        recordType: typeMatch[1].toUpperCase(),
        status: status ?? undefined,
        courtName: courtName ?? undefined,
        referenceNumber: referenceNumber ?? undefined,
        dateFiled,
        amount,
      });
    }
  }
  return out;
}

// ── Field extractors ────────────────────────────────────────────────────
function labelValue(block: string, labels: string[]): string | undefined {
  for (const label of labels) {
    const re = new RegExp(
      `\\b${escapeRegex(label)}\\s*[:\\-]\\s*([^\\n]+?)(?:\\n|$)`,
      "i",
    );
    const m = block.match(re);
    if (m) {
      const v = m[1].trim();
      if (v.length > 0 && v.toLowerCase() !== "n/a" && v !== "—") return v;
    }
  }
  return undefined;
}

function currencyValue(block: string, labels: string[]): number | undefined {
  for (const label of labels) {
    const re = new RegExp(
      `\\b${escapeRegex(label)}\\s*[:\\-]?\\s*\\$?([\\d,]+(?:\\.\\d{2})?)\\b`,
      "i",
    );
    const m = block.match(re);
    if (m) {
      const n = Number(m[1].replace(/,/g, ""));
      if (!Number.isNaN(n) && n >= 0 && n < 1e10) return n;
    }
  }
  return undefined;
}

function dateValue(block: string, labels: string[]): string | undefined {
  for (const label of labels) {
    const re = new RegExp(
      `\\b${escapeRegex(label)}\\s*[:\\-]?\\s*(\\d{1,2}[\\/\\-]\\d{1,2}[\\/\\-]\\d{2,4})`,
      "i",
    );
    const m = block.match(re);
    if (m) return isoDate(m[1]);
  }
  return undefined;
}

function isoDate(raw: string): string | undefined {
  const m = raw.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);
  if (!m) return undefined;
  let yyyy = Number(m[3]);
  if (yyyy < 100) yyyy += yyyy < 50 ? 2000 : 1900;
  const mm = String(Number(m[1])).padStart(2, "0");
  const dd = String(Number(m[2])).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

function canonicalBureau(raw: string): Bureau | undefined {
  const k = raw.toLowerCase().replace(/\s+/g, "");
  if (k === "experian") return "Experian";
  if (k === "equifax") return "Equifax";
  if (k === "transunion") return "TransUnion";
  return undefined;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
